name: "Check artifact existence"
description: "Check existence of an artifact uploaded in the workflow by the upload-artifact action"
author: "Yurii Serhiichuk"
inputs:
  name:
    description: "Artifact name"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "file"
  color: "white"
