name: Test Workflow with our Action and and Upload Artifact v4 (does not work)

on:
  workflow_dispatch:
  pull_request:
  push:
jobs:
  run-action:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Store Workflow
        uses: actions/upload-artifact@v4
        with:
          name: "test-workflow"
          path: ".github/workflows/test-workflow-with-action-upload-v4.yaml"
          retention-days: 3
      - uses: "./"
        name: "Check artifact exists"
        id: "check_workflow_exists"
        with:
          name: "test-workflow"
      - uses: "./"
        name: "Check artifact does not exist"
        id: "check_non_existing"
        with:
          name: "non-existing-artifact"
      - name: "Echo if artifact exists"
        run: echo "::notice::Artifact in-deed exists."
        if: "${{ steps.check_workflow_exists.outputs.exists == 'true' }}"
      - name: "Echo if artifact does not exist"
        run: echo "::notice::Artifact in-deed does not exist."
        if: "${{ steps.check_non_existing.outputs.exists == 'false' }}"
